# Generated by Django 2.2 on 2020-04-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0003_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='p2p',
            old_name='send_to',
            new_name='receiver',
        ),
    ]
