# Generated by Django 2.2 on 2020-03-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='registration',
            name='password2',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
