# Generated by Django 2.2 on 2020-03-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200319_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='password2',
        ),
    ]
